# Dockstore config version, not pipeline version
version: 1.2
workflows:
  - name: SG10K-lcWGS
    subclass: nfl
    primaryDescriptorPath: /nextflow.config
    publish: True
    authors:
      - name: Justin Jeyakani
        email: gnanakkan@gis.a-star.edu.sg
        orcid: 0000-0002-1788-0417
      - name: Mar Gonzalez-Porta
        email: mar@nalagenetics.com
        orcid: 0000-0002-1661-7254  
      - name: Maxime HEBRARD
        email: Maxime_Hebrard@gis.a-star.edu.sg
        orcid: 0000-0003-2346-4513
      - name: Nicolas Bertin
        email: Nicolas_Bertin@gis.a-star.edu.sg
        orcid: 0000-0002-9835-9606
      - name: Kevin Nathanael Ramanto
        email: kevin@nalagenetics.com
    filters:
      branches: 
        - main
        - master
        - develop
      tags:
        - /.*/
